[profile.local]
eth-rpc-url = 'http://localhost:8545'

[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "tron/=lib/tron/src",
    "tronLib/=lib/tron/lib",
    "tronTest/=lib/tron/test",
    "tronScripts/=lib/tron/script",
    "axelar-gmp-sdk-solidity/=lib/axelar-gmp-sdk-solidity/contracts/",
]

[rpc_endpoints]
local_chain_1 = "http://localhost:8545"
local_chain_2 = "http://localhost:8546"
amoy_chain = "https://rpc-amoy.polygon.technology"
sepolia_chain = "https://ethereum-sepolia-rpc.publicnode.com"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
