[profile.local]
eth-rpc-url = 'http://localhost:8545'

[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/",
    "@forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "rulesEngine/=lib/ruleEngine/src",
    "rulesEngineLib/=lib/ruleEngine/lib",
    "rulesEngineTest/=lib/ruleEngine/test",
    "rulesEngineScripts/=lib/ruleEngine/script",
    "axelar-gmp-sdk-solidity/=lib/axelar-gmp-sdk-solidity/contracts/",
    "@axelar-network/axelar-gmp-sdk-solidity/=lib/axelar-gmp-sdk-solidity",
    "forte-rules-engine/=lib/forte-rules-engine/src/"
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
