[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "tron/=lib/tron/src",
    "tronLib/=lib/tron/lib",
    "tronTest/=lib/tron/test",
    "tronScripts/=lib/tron/script"
]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
