name: Composite Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]
permissions:
  contents: read
  pull-requests: write
jobs:
  test:
    uses: Forte-Service-Company-Ltd/infrastructure-tooling/.github/workflows/onchain-build-test-report.yaml@v0.0.1
    secrets: inherit
    with:
      markdown-file-path: "./README.md"
      salt-string: "SMELLING_SALTS"
      skip-forte-token-tests: true
      fork-test: false
