name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TRON_GITHUB_TOKEN }}
          submodules: recursive

      - name: Create Foundry Dir
        run: |
          mkdir -p $HOME/.foundry/bin/
          echo "$HOME/.foundry/bin" >> $GITHUB_PATH

      - name: Install Foundry
        run: |
          curl -sSL https://raw.githubusercontent.com/thrackle-io/foundry/refs/heads/master/foundryup/foundryup -o $HOME/.foundry/bin/foundryup
          chmod +x $HOME/.foundry/bin/foundryup
          foundryup --version $(awk '$1~/^[^#]/' foundry.lock)

      - name: Install dependencies
        run: |
          git config user.email "cloudops@thrackle.io"
          git config user.name "CloudOps Thrackle"
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install eth_abi
          forge install dapphub/ds-test 

      - name: Build
        run: |
          forge clean && forge build --optimize

      - name: Test
        env:
          FORK_TEST: false
          SALT_STRING: "SMELLING_SALTS"
        run: |
          forge test -vv --ffi
