name: Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, edited, ready_for_review]

env:
  FOUNDRY_PROFILE: ci

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: v1.2.1
      - name: Clone repository dependencies
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt
          forge install
      - name: Build the repository
        shell: bash
        run: |
          forge clean && forge build --optimize

      - name: Install dependencies
        run: |
          git config user.email "cloudops@thrackle.io"
          git config user.name "CloudOps Thrackle"
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install eth_abi
          forge install dapphub/ds-test 

      - name: Build
        run: |
          forge clean && forge build --optimize

      - name: Test
        env:
          FORK_TEST: false
          SALT_STRING: "SMELLING_SALTS"
        run: |
          forge test -vv --ffi
